"""changing data type of the date column in our transactions table

Revision ID: 3ffc578cd625
Revises: 
Create Date: 2026-08-10 12:12:04.096321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffc578cd625'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
